DROP TABLE JOB;
DROP TABLE PERSON;
DROP SEQUENCE PERSON_PNO_SQ;

-- 테이블 및 시퀀스 생성
CREATE TABLE JOB (
    jNO NUMBER(2) PRIMARY KEY,
    jNAME VARCHAR2(30) NOT NULL
);
CREATE SEQUENCE PERSON_PNO_SQ MAXVALUE 99999 NOCACHE NOCYCLE;
CREATE TABLE PERSON (
    pNO NUMBER(5) PRIMARY KEY,
    pNAME VARCHAR2(30) NOT NULL,
    jNO NUMBER(2) NOT NULL,
    KOR NUMBER(3) CHECK(KOR>=0 AND KOR<=100),
    ENG NUMBER(3) CHECK(ENG>=0 AND ENG<=100),
    MAT NUMBER(3) CHECK(MAT>=0 AND MAT<=100),
    FOREIGN KEY (jNO) REFERENCES JOB(jNO)
    );
-- DUMMY DATA
-- JOB (10, 배우), (20, 가수), (30,MC)
INSERT INTO JOB (jNO, jNAME) VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, 'MC');

SELECT * FROM JOB;

-- PERSON 문 삽입
INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '정우성', '10', 90, 80, 81);
INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '박세영', '20', 80, 90, 80);
INSERT INTO PERSON VALUES (PERSON_PNO_SQ.NEXTVAL, '정우성', '10', 90, 80, 81);
ROLLBACK;
SELECT * FROM PERSON;
COMMIT;