DROP TABLE MEMBER;
DROP TABLE CART;
DROP TABLE PRODUCT;
DROP TABLE ORDERS;
DROP TABLE ORDER_DETAILS;

CREATE TABLE MEMBER(
    mID VARCHAR2(50) PRIMARY KEY,
    mNAME VARCHAR2(50) NOT NULL,
    mADDR VARCHAR2(255),
    mTEL NUMBER(12),
    mEMAIL VARCHAR2(255) NOT NULL UNIQUE
);

CREATE TABLE PRODUCT (
    pCODE VARCHAR2(50) PRIMARY KEY,
    pNAME VARCHAR2(50),
    PRICE NUMBER CHECK(PRICE>0),
    pSTOCK NUMBER CHECK(pSTOCK>=0)
);
CREATE TABLE CART (
    cNO NUMBER(4) PRIMARY KEY,
    mID VARCHAR2(50) NOT NULL,
    pCODE VARCHAR2(50) NOT NULL,
    QTY NUMBER(4) NOT NULL,
    COST NUMBER(5),
    FOREIGN KEY (mID) REFERENCES MEMBER(mID),
    FOREIGN KEY (pCODE) REFERENCES PRODUCT(pCODE)
);
CREATE TABLE ORDERS(
    oNO NUMBER(4) PRIMARY KEY,
    mID VARCHAR2(50) NOT NULL,
    oNAME VARCHAR2(50) NOT NULL,
    oADDR VARCHAR2(255) NOT NULL,
    oTEL NUMBER(13) NOT NULL,
    oDATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (mID) REFERENCES MEMBER(mID)
);
CREATE TABLE ORDERS_DETAILS(
    odNO NUMBER(4) PRIMARY KEY,
    oNO NUMBER(4) NOT NULL,
    pCODE VARCHAR2(50) NOT NULL,
    QTY NUMBER(4) NOT NULL,
    COST NUMBER(5)
);

INSERT INTO MEMBER (mID, mNAME, mADDR, mTEL, mEMAIL)
    VALUES('ABC', '홍길동', '서울시 관악구 신림동', '010-9999-9999', 'HONG@HONG.COM');
SELECT * FROM MEMBER;