-- PDF 연습문제
DROP TABLE MAJOR;
DROP TABLE STUDENT;
CREATE TABLE MAJOR (
    MAJOR_CODE NUMBER(2) NOT NULL,
    MAJOR_NAME VARCHAR2(50) UNIQUE,
    MAJOR_OFFICE_LOC VARCHAR2(255) NOT NULL
);
CREATE TABLE STUDENT (
    STUDENT_CODE VARCHAR2(10) NOT NULL,
    STUDENT_NAME VARCHAR2(50) NOT NULL,
    SCORE NUMBER CHECK (SCORE BETWEEN 0 AND 100),
    MAJOR_CODE NUMBER(2)
);
INSERT INTO MAJOR (MAJOR_CODE, MAJOR_NAME, MAJOR_OFFICE_LOC)
    VALUES(1, '컴퓨터 공학', 'A101호');
INSERT INTO MAJOR VALUES (2, '빅데이터', 'A102호');
SELECT * FROM MAJOR;

INSERT INTO STUDENT (STUDENT_CODE, STUDENT_NAME, SCORE, MAJOR_CODE)
    VALUES (101, '홍길동', 99, '1');
INSERT INTO STUDENT VALUES(102, '신길동', 100, '2');
SELECT STUDENT_CODE, STUDENT_NAME, SCORE, M.MAJOR_CODE, MAJOR_NAME, MAJOR_OFFICE_LOC
    FROM MAJOR M, STUDENT S
    WHERE M.MAJOR_CODE=S.MAJOR_CODE;